version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/postrges:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    build:
      context: .
      dockerfile: KeycloakDockerfile
    container_name: keycloak
    volumes:
      - ./govuk/:/opt/jboss/keycloak/themes/govuk/
      - ./govuk-internal/:/opt/jboss/keycloak/themes/govuk-internal/
      - ./govuk-social-providers/:/opt/jboss/keycloak/themes/govuk-social-providers/
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres        
      - maildev
  maildev:
    container_name: maildev
    image: djfarrelly/maildev:1.0.0-rc2
    ports:
      - "8081:80"
      - "25"
